version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud_app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/agendaDB
    depends_on:
      - mongo

volumes:
  mongo_data:
